### ISSUE TITLE
Component Placement

### ISSUE THREAD

**Issue by Typhonragewind** [xyzroe/ZigUSB#1]
Hello! 

Would it be possible for you to provide the component placement on the board, please? I'm having a hard time figuring it out by the images on the repo.

**Comment by xyzroe** [comment]
@Typhonragewind look [here](https://xyzroe.cc/ZigUSB/hardware/zigbee_usb_power_switch_final_rev0.html)

**Comment by Typhonragewind** [comment]
> @Typhonragewind look [here](https://xyzroe.cc/ZigUSB/hardware/zigbee_usb_power_switch_final_rev0.html)

Omg, i'm blind. Thank you so much!

**Comment by xyzroe** [comment]
> > @Typhonragewind look [here](https://xyzroe.cc/ZigUSB/hardware/zigbee_usb_power_switch_final_rev0.html)
> 
> Omg, i'm blind. Thank you so much!

Everything is ok with you. I just added this)
